// Generated from yfinance const.py (https://github.com/ranaroussi/yfinance)
// Licensed under Apache 2.0 by Ran Aroussi.

pub static SECTOR_INDUSTRY_MAP: phf::Map<&'static str, &'static [&'static str]> = phf::phf_map! {
    "Basic Materials" => &[
        "Specialty Chemicals",
        "Gold",
        "Building Materials",
        "Copper",
        "Steel",
        "Agricultural Inputs",
        "Chemicals",
        "Other Industrial Metals & Mining",
        "Lumber & Wood Production",
        "Aluminum",
        "Other Precious Metals & Mining",
        "Coking Coal",
        "Paper & Paper Products",
        "Silver",
    ],
    "Communication Services" => &[
        "Advertising Agencies",
        "Broadcasting",
        "Electronic Gaming & Multimedia",
        "Entertainment",
        "Internet Content & Information",
        "Publishing",
        "Telecom Services",
    ],
    "Consumer Cyclical" => &[
        "Apparel Manufacturing",
        "Apparel Retail",
        "Auto & Truck Dealerships",
        "Auto Manufacturers",
        "Auto Parts",
        "Department Stores",
        "Footwear & Accessories",
        "Furnishings Fixtures & Appliances",
        "Gambling",
        "Home Improvement Retail",
        "Internet Retail",
        "Leisure",
        "Lodging",
        "Luxury Goods",
        "Packaging & Containers",
        "Personal Services",
        "Recreational Vehicles",
        "Residential Construction",
        "Resorts & Casinos",
        "Restaurants",
        "Specialty Retail",
        "Textile Manufacturing",
        "Travel Services",
    ],
    "Consumer Defensive" => &[
        "Beverages \u{2014} Brewers",
        "Beverages \u{2014} Non-Alcoholic",
        "Beverages \u{2014} Wineries & Distilleries",
        "Confectioners",
        "Discount Stores",
        "Education & Training Services",
        "Farm Products",
        "Food Distribution",
        "Grocery Stores",
        "Household & Personal Products",
        "Packaged Foods",
        "Tobacco",
    ],
    "Energy" => &[
        "Oil & Gas Drilling",
        "Oil & Gas E&P",
        "Oil & Gas Equipment & Services",
        "Oil & Gas Integrated",
        "Oil & Gas Midstream",
        "Oil & Gas Refining & Marketing",
        "Thermal Coal",
        "Uranium",
    ],
    "Financial Services" => &[
        "Asset Management",
        "Banks \u{2014} Diversified",
        "Banks \u{2014} Regional",
        "Capital Markets",
        "Credit Services",
        "Financial Conglomerates",
        "Financial Data & Stock Exchanges",
        "Insurance Brokers",
        "Insurance \u{2014} Diversified",
        "Insurance \u{2014} Life",
        "Insurance \u{2014} Property & Casualty",
        "Insurance \u{2014} Reinsurance",
        "Insurance \u{2014} Specialty",
        "Mortgage Finance",
        "Shell Companies",
    ],
    "Healthcare" => &[
        "Biotechnology",
        "Diagnostics & Research",
        "Drug Manufacturers \u{2014} General",
        "Drug Manufacturers \u{2014} Specialty & Generic",
        "Health Information Services",
        "Healthcare Plans",
        "Medical Care Facilities",
        "Medical Devices",
        "Medical Instruments & Supplies",
        "Medical Distribution",
        "Pharmaceutical Retailers",
    ],
    "Industrials" => &[
        "Aerospace & Defense",
        "Airlines",
        "Airports & Air Services",
        "Building Products & Equipment",
        "Business Equipment & Supplies",
        "Conglomerates",
        "Consulting Services",
        "Electrical Equipment & Parts",
        "Engineering & Construction",
        "Farm & Heavy Construction Machinery",
        "Industrial Distribution",
        "Infrastructure Operations",
        "Integrated Freight & Logistics",
        "Marine Shipping",
        "Metal Fabrication",
        "Pollution & Treatment Controls",
        "Railroads",
        "Rental & Leasing Services",
        "Security & Protection Services",
        "Specialty Business Services",
        "Specialty Industrial Machinery",
        "Staffing & Employment Services",
        "Tools & Accessories",
        "Trucking",
        "Waste Management",
    ],
    "Real Estate" => &[
        "Real Estate \u{2014} Development",
        "Real Estate Services",
        "Real Estate \u{2014} Diversified",
        "REIT \u{2014} Healthcare Facilities",
        "REIT \u{2014} Hotel & Motel",
        "REIT \u{2014} Industrial",
        "REIT \u{2014} Office",
        "REIT \u{2014} Residential",
        "REIT \u{2014} Retail",
        "REIT \u{2014} Mortgage",
        "REIT \u{2014} Specialty",
        "REIT \u{2014} Diversified",
    ],
    "Technology" => &[
        "Communication Equipment",
        "Computer Hardware",
        "Consumer Electronics",
        "Electronic Components",
        "Electronics & Computer Distribution",
        "Information Technology Services",
        "Scientific & Technical Instruments",
        "Semiconductor Equipment & Materials",
        "Semiconductors",
        "Software \u{2014} Application",
        "Software \u{2014} Infrastructure",
        "Solar",
    ],
    "Utilities" => &[
        "Utilities \u{2014} Diversified",
        "Utilities \u{2014} Independent Power Producers",
        "Utilities \u{2014} Regulated Electric",
        "Utilities \u{2014} Regulated Gas",
        "Utilities \u{2014} Regulated Water",
        "Utilities \u{2014} Renewable",
    ],
};
